openapi: 3.0.1
info:
  title: Template API
  description: Sample API for Spring Boot OpenAPI code generation
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /hello:
    get:
      summary: Returns a greeting message
      operationId: getHello
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
          example: Hello, World!

